In [1]:
import pandas as pd
import os
from multiprocessing import Pool
import numpy as np
import math
from sklearn.base import BaseEstimator, TransformerMixin

In [3]:
def create_combined_dataset(path_to_raw_data_folder):
    
    data = [pd.read_csv(f'{path_to_raw_data_folder}/{i}'
                        , low_memory = False) 
            for i in os.listdir(path_to_raw_data_folder) if i.endswith('.csv')]
    return pd.concat(data)
    
    
def read_one(path):
    return pd.read_csv(path, low_memory = False)


def build_dataset():
    features= ['title'
            , 'installment'
    ]
    df = create_combined_dataset('lending_club_data')
    return df[features]

In [4]:
df = build_dataset()

In [63]:
df['title']=df['title'].fillna('')

In [64]:
df['title'].unique()

array(['Credit card refinancing', 'Debt consolidation', 'Car financing',
       'Other', 'Vacation', 'Home improvement', 'Home buying',
       'Major purchase', 'Business', 'Green loan', 'Medical expenses',
       'Moving and relocation', ' '], dtype=object)

In [65]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.impute import SimpleImputer, MissingIndicator
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

In [78]:
#construct transformer
vect = TfidfVectorizer(analyzer='word',stop_words= 'english')

#transform the vectorizer on the title column
tfidf_matrix = vect.fit_transform(df['title'])

#print the TFIDF matrix to an array and add the features as columns
df1 = pd.DataFrame(tfidf_matrix.toarray(), columns = vect.get_feature_names())

#print out the result
print(df1)

        business  buying  car     card  consolidation   credit      debt  \
0            0.0     0.0  0.0  0.57735       0.000000  0.57735  0.000000
1            0.0     0.0  0.0  0.57735       0.000000  0.57735  0.000000
2            0.0     0.0  0.0  0.57735       0.000000  0.57735  0.000000
3            0.0     0.0  0.0  0.57735       0.000000  0.57735  0.000000
4            0.0     0.0  0.0  0.00000       0.707107  0.00000  0.707107
...          ...     ...  ...      ...            ...      ...       ...
128411       0.0     0.0  0.0  0.00000       0.000000  0.00000  0.000000
128412       0.0     0.0  0.0  0.00000       0.000000  0.00000  0.000000
128413       0.0     0.0  0.0  0.00000       0.000000  0.00000  0.000000
128414       0.0     0.0  0.0  0.00000       0.000000  0.00000  0.000000
128415       0.0     0.0  0.0  0.00000       0.000000  0.00000  0.000000

        expenses  financing  green  home  improvement  loan  major  medical  \
0            0.0        0.0    0.0   0.0          0.0   0.0    0.0      0.0
1            0.0        0.0    0.0   0.0          0.0   0.0    0.0      0.0
2            0.0        0.0    0.0   0.0          0.0   0.0    0.0      0.0
3            0.0        0.0    0.0   0.0          0.0   0.0    0.0      0.0
4            0.0        0.0    0.0   0.0          0.0   0.0    0.0      0.0
...          ...        ...    ...   ...          ...   ...    ...      ...
128411       0.0        0.0    0.0   0.0          0.0   0.0    0.0      0.0
128412       0.0        0.0    0.0   0.0          0.0   0.0    0.0      0.0
128413       0.0        0.0    0.0   0.0          0.0   0.0    0.0      0.0
128414       0.0        0.0    0.0   0.0          0.0   0.0    0.0      0.0
128415       0.0        0.0    0.0   0.0          0.0   0.0    0.0      0.0

        moving  purchase  refinancing  relocation  vacation
0          0.0       0.0      0.57735         0.0       0.0
1          0.0       0.0      0.57735         0.0       0.0
2          0.0       0.0      0.57735         0.0       0.0
3          0.0       0.0      0.57735         0.0       0.0
4          0.0       0.0      0.00000         0.0       0.0
...        ...       ...          ...         ...       ...
128411     0.0       0.0      0.00000         0.0       0.0
128412     0.0       0.0      0.00000         0.0       0.0
128413     0.0       0.0      0.00000         0.0       0.0
128414     0.0       0.0      0.00000         0.0       0.0
128415     0.0       0.0      0.00000         0.0       0.0

[128416 rows x 20 columns]

In [80]:
#transform result into a dataframe
pd.DataFrame(df1)

,business,buying,car,card,consolidation,credit,debt,expenses,financing,green,home,improvement,loan,major,medical,moving,purchase,refinancing,relocation,vacation
0,0.0,0.0,0.0,0.57735,0.000000,0.57735,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.57735,0.0,0.0
1,0.0,0.0,0.0,0.57735,0.000000,0.57735,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.57735,0.0,0.0
2,0.0,0.0,0.0,0.57735,0.000000,0.57735,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.57735,0.0,0.0
3,0.0,0.0,0.0,0.57735,0.000000,0.57735,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.57735,0.0,0.0
4,0.0,0.0,0.0,0.00000,0.707107,0.00000,0.707107,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128411,0.0,0.0,0.0,0.00000,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0
128412,0.0,0.0,0.0,0.00000,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0
128413,0.0,0.0,0.0,0.00000,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0
128414,0.0,0.0,0.0,0.00000,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0
128415,0.0,0.0,0.0,0.00000,0.000000,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0

Extra Credit Question
1. Find out the difference between feature='all' and feature='missing only' on the missing indicator
-- Answer: This determins wether the imputer should mask all featurs or only a subset of features. If “missing-only', the imputer mask will only represent features containing missing values during fit time. If “all”, the imputer mask will represent all features